Repository daisybio/drevalpy, pull requests merged in 2024-11, with the labels that each got.

#70 Typeguard fix
  .github/workflows/run_tests.yml
  drevalpy/datasets/dataset.py
  drevalpy/datasets/loader.py
  drevalpy/datasets/utils.py
  drevalpy/evaluation.py
  drevalpy/experiment.py
  drevalpy/models/MOLIR/molir.py
  drevalpy/models/MOLIR/utils.py
  drevalpy/models/SimpleNeuralNetwork/multiomics_neural_network.py
  drevalpy/models/SimpleNeuralNetwork/simple_neural_network.py
  drevalpy/models/SimpleNeuralNetwork/utils.py
  drevalpy/models/SuperFELTR/superfeltr.py
  drevalpy/models/SuperFELTR/utils.py
  drevalpy/models/baselines/multi_omics_random_forest.py
  drevalpy/models/baselines/naive_pred.py
  drevalpy/models/baselines/singledrug_random_forest.py
  drevalpy/models/baselines/sklearn_models.py
  drevalpy/models/drp_model.py
  drevalpy/models/utils.py
  drevalpy/visualization/utils.py
  poetry.lock
  pyproject.toml
  requirements.txt
  tests/individual_models/test_baselines.py
  tests/individual_models/test_molir_superfeltr.py
  tests/individual_models/test_simple_neural_network.py
  tests/test_dataset.py
  tests/test_evaluation.py
  tests/test_run_suite.py
Labels: bug, enhancement, ci

#72 Mypy fix
  create_report.py
  drevalpy/datasets/dataset.py
  drevalpy/datasets/loader.py
  drevalpy/evaluation.py
  drevalpy/experiment.py
  drevalpy/models/MOLIR/molir.py
  drevalpy/models/MOLIR/utils.py
  drevalpy/models/SRMF/srmf.py
  drevalpy/models/SimpleNeuralNetwork/multiomics_neural_network.py
  drevalpy/models/SimpleNeuralNetwork/simple_neural_network.py
  drevalpy/models/SimpleNeuralNetwork/utils.py
  drevalpy/models/SuperFELTR/hyperparameters.yaml
  drevalpy/models/SuperFELTR/superfeltr.py
  drevalpy/models/SuperFELTR/utils.py
  drevalpy/models/__init__.py
  drevalpy/models/baselines/multi_omics_random_forest.py
  drevalpy/models/baselines/naive_pred.py
  drevalpy/models/baselines/singledrug_random_forest.py
  drevalpy/models/baselines/sklearn_models.py
  drevalpy/models/drp_model.py
  drevalpy/models/utils.py
  drevalpy/visualization/corr_comp_scatter.py
  drevalpy/visualization/critical_difference_plot.py
  drevalpy/visualization/html_tables.py
  drevalpy/visualization/outplot.py
  drevalpy/visualization/regression_slider_plot.py
  drevalpy/visualization/utils.py
  drevalpy/visualization/vioheat.py
  noxfile.py
  poetry.lock
  pyproject.toml
  tests/individual_models/test_baselines.py
  tests/individual_models/test_molir_superfeltr.py
  tests/individual_models/test_simple_neural_network.py
  tests/test_dataset.py
  tests/test_drp_model.py
Labels: bug

#83 fix DIPK attention layer unable to process batches of size 1
  drevalpy/models/DIPK/gene_expression_encoder.py
  drevalpy/models/DIPK/model_utils.py
Labels: bug

#84 Feature/curvecurator
  .github/workflows/build_package.yml
  .github/workflows/publish_docs.yml
  .github/workflows/run_tests.yml
  docs/API.rst
  docs/conf.py
  docs/requirements.txt
  drevalpy/datasets/curvecurator.py
  drevalpy/datasets/dataset.py
  drevalpy/datasets/loader.py
  drevalpy/utils.py
  noxfile.py
  poetry.lock
  pyproject.toml
  requirements.txt
  setup.cfg
  tests/CTRPv2_sample_test/CTRPv2_sample_test_raw.csv
  tests/test_dataset.py
  tests/test_run_suite.py
Labels: enhancement

#86 Fixed MOLIR, also pushing current state of documentation
  .github/workflows/publish_docs.yml
  .github/workflows/python-package.yml
  .readthedocs.yml
  Dockerfile
  README.md
  docs/API.rst
  docs/_key_contributors.rst
  docs/_static/custom_cookietemple.css
  docs/conf.py
  docs/contributing.rst
  docs/drevalpy.datasets.rst
  docs/drevalpy.models.DIPK.rst
  docs/drevalpy.models.MOLIR.rst
  docs/drevalpy.models.SRMF.rst
  docs/drevalpy.models.SimpleNeuralNetwork.rst
  docs/drevalpy.models.SuperFELTR.rst
  docs/drevalpy.models.baselines.rst
  docs/drevalpy.models.rst
  docs/drevalpy.visualization.rst
  docs/index.rst
  docs/installation.rst
  docs/jobs.rst
  docs/news.rst
  docs/outputs.rst
  docs/quickstart.rst
  docs/usage.rst
  drevalpy/models/MOLIR/utils.py
  drevalpy/models/SRMF/srmf.py
  drevalpy/utils.py
  drevalpy/visualization/corr_comp_scatter.py
  poetry.lock
  pyproject.toml
  setup.py
Labels: bug, chore
